//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invitation
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public Nullable<int> UserId { get; set; }
        public System.DateTime Date { get; set; }
        public int ParticipantTypeId { get; set; }
        public string Email { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual ParticipantType ParticipantType { get; set; }
        public virtual User User { get; set; }
    }
}
